### PR TITLE
Update app-fqdn-rules.tf

### PR DESCRIPTION
**Pull request by iamtinker**
## Description
update filter rule

### CODE REVIEW

**Review by bdu2000 — APPROVED** [review]

**Review by bdu2000 — DISMISSED** [review]
looks good

**Review by briandu2022 — APPROVED** [review]

**Review by briandu2022 — CHANGES_REQUESTED** [review]
test

**Review by iamtinker — COMMENTED** [review]
sdfg

**Review by briandu2022 — CHANGES_REQUESTED** [review]
asdgf

**Review by iamtinker — COMMENTED** [review]
sdfg

**Review by briandu2022 — APPROVED** [review]
asdf

**Comment by briandu2022** [comment]
finished

**Comment by briandu2022** [comment]
asdf

**Comment by briandu2022** [comment]
asdf

**Pull request closed without merging**
